name: Deploy CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build and Deploy
      run: |
        eval `ssh-agent -s`
        ssh-add <(echo "${{ secrets.PROD_KEY }}")
        rsync -Prtgovze "ssh -o StrictHostKeyChecking=no" --no-perms --no-owner --no-group $GITHUB_WORKSPACE/ ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }}:${{ secrets.PROD_PATH }}/
      #  ssh -o StrictHostKeyChecking=no ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }} "cd ${{ secrets.PROD_PATH }} && ls -al"
      #  rsync -Prtgovze "ssh -o StrictHostKeyChecking=no" --no-perms --no-owner --no-group --delete-after $GITHUB_WORKSPACE ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }}:${{ secrets.PROD_PATH }}/
      #  ssh -o StrictHostKeyChecking=no ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }} "cd ${{ secrets.PROD_PATH }} && ls -al"
      env:
        CI: true
